spring:
  datasource:
    oracle:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: nav
      password: nav
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:oracle:thin:@127.0.0.1:49161/xe

    sqlserver:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: DBQuery
      password: DBQuery123
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=nav

